### ISSUE TITLE
Tags are incorrectly truncated in OSM line shapefile

### ISSUE THREAD

**Issue by kkwteh** [mapzen/chef-metroextractor#19]
For instance, let's say I load the Dallas, TX OSM line shapefile into my database using shp2pgs2l:

```$ shp2pgsql -I -s 4326 -c /tmp/dallas_texas_osm_line public.road_geometries | psql postgres://:@localhost:5432/my_db```

Inspecting the tags in the database, we see that some of the values in the tags column are abruptly truncated.

For example if I query

```
SELECT name, osm_id, tags FROM road_geometries WHERE osm_id = 10022714
```

The result is:

```
name   | Edgehill Road
osm_id | 10022714
tags   | "tiger:cfcc"=>"A41", "tiger:tlid"=>"103516618:103532208:103516622:103556965:103556966:225914365:103532156", "tiger:county"=>"Johnson, TX", "tiger:source"=>"tiger_import_dch_v0.6_20070830", "tiger:reviewed"=>"no", "tiger:zip_left"=>"76028", "tiger:name_ba
```

And the last visible tag, `"tiger:name_ba` is truncated.

These truncated tags make the data less usable, because I suspect the truncation is omitting some of the tags that are present in the source data, and it makes it difficult to parse out individual tags for instance by converting the field to hstore type.

**Comment by heffergm** [comment]
@rmarianski && @zerebubuth, ever run across this sort of thing?

**Comment by zerebubuth** [comment]
I had a go at reproducing this, and `pgsql2shp` segfaulted!

Although I've not run across this exact issue before, it sounds very similar to some issues I've seen around Shapefile format limitations. In particular, a `Text` format field is [limited to 254 characters](http://resources.arcgis.com/en/help/main/10.1/index.html#//005600000013000000#GUID-A10ADA3B-0988-4AB1-9EBA-AD704F77B4A2), and in the example above the `a` at the end of `tiger:name_ba` is the 254th character.

Unfortunately, I can't confirm that this is the case, but it seems likely.

I was able to extract data with long values directly to GeoJSON with the following:

```
ogr2ogr -f "GeoJSON" foo.geojson PG:dbname=mapzen foo
```

(Where `foo` was a subset table of `planet_osm_line` with 8 rows but very long `tags::text`). Might it be worth generating the GeoJSON from the database, and then the Shapefile from the GeoJSON? At the moment we [do it the other way around](https://github.com/mapzen/chef-metroextractor/blob/master/templates/default/shapes.sh.erb#L19-L27) so GeoJSON ends up inheriting Shapefile's limitations.

Some sources refer to a `.dbt` file or "memo" file which can be created alongside the `.dbf` for holding longer text fields, but it looks like it's [not supported](https://github.com/postgis/postgis/blob/f6ed58d1fdc865d55d348212d02c11a10aeb2b30/loader/shapefil.h#L528-L535) by `pgsql2shp` or [OGR](https://github.com/OSGeo/gdal/blob/trunk/gdal/ogr/ogrsf_frmts/shape/ogrshapelayer.cpp#L1722-L1733).

**Comment by heffergm** [comment]
Thanks for checking it out. I'd say the character limitation is likely given the 'coincidence'. 

@kkwteh I will add a feature request to look into changing the processing order in the future.
