### ISSUE TITLE
Wrong character encoding in warsaw-poland.imposm-geojson

### ISSUE THREAD

**Issue by michal-gh** [mapzen/chef-metroextractor#8]
Hi,
There's a problem with UTF-8 character encoding in imposm-geojson files. For instance, a fragment of the warsaw_poland-admin.geojson file looks like:

{ "type": "Feature", "properties": { "id": 2.0, "osm_id": -336132.0, "name": "JÃ³zefosÅaw", "type": "administrative", "admin_leve": 8.0 }, "geometry": { "type": "Polygon", "coordinates"

but the name of this area should be: "Józefosław". 
This name is correctly encoded in warsaw_poland.osm-admin.dbf file, so it seems it's getting mangled during conversion to geojson format.

**Comment by heffergm** [comment]
Hi,
Thanks for reporting this, you are indeed correct in that there was an issue in the encoding when converting to geojson. Should be fixed now, and new data is being uploaded:

From warsaw_poland-admin.geojson:
{ "id": 9.0, "osm_id": -336132.0, "name": "Józefosław", "type": "administrative", "admin_leve": 8.0 }
